services:
  app:
    build:
      context: ./project/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - ./project/.env
    networks:
      - backend
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  db-data:

networks:
  frontend:
  backend: