services:
  app:
    build:
      context: ./project/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./project/gutendex/.env
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=gutendex
      - POSTGRES_DB=gutendex
    networks:
      - backend
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    

volumes:
  db-data:

networks:
  frontend:
  backend: